import Head from 'next/head'
import { TemplateSite } from '../components/_templates/Site'
export default function Home() {
  return (
    <TemplateSite>
      <Head>
        <title>InGlobal Desenvolvimento</title>
      </Head>
      <p>Primeira linha de</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>Conteúdo do site</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
      <p>outra coisaaaaaa aquiiiiiiiiiiiii</p>
    </TemplateSite>
  )
}
